---
fix: false
format: progress # default: Standard::Formatter
default_ignores: false # default: true

ignore:
  - 'vendor/bundle/**/*'
  - lib/trino/client/model_versions/0.149.rb
  - lib/trino/client/model_versions/0.153.rb
  - lib/trino/client/model_versions/0.173.rb
  - lib/trino/client/model_versions/0.178.rb
  - lib/trino/client/model_versions/0.205.rb
  - lib/trino/client/model_versions/303.rb
  - lib/trino/client/model_versions/316.rb
  - lib/trino/client/model_versions/351.rb
